### ISSUE TITLE
Endpoints route improvements

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare#1006]
The routes for Endpoints are kind of wierd right now.

Current path: `https://logflare.app/endpoints/query/UUID`

- [ ] `https://logflare.app/endpoints/UUID_OR_NAME_OR_ID/query`
- [ ] `https://logflare.app/endpoints/UUID_OR_NAME_OR_ID/query/result` should only be the data in the `result`
- [ ] Let's include some metadata about the query on `/query` (the query string itself, passed in params, resp time, total bytes billed, if an error occurred include the error message maybe)
- [ ] 🚨  must be backward compatible for a period of time 🚨

**Comment by Ziinc** [comment]
For this issue, i think it would be good to scope names to teams. That way, we can swap out the logflare url for different environments and still point to the same name.

For example, `https://logflare.app/endpoints/TEAM_NAME/UUID_OR_NAME/...`
that way, the only part that needs to be swapped out between env is `https://logflare.app/endpoints/TEAM_NAME`

**Comment by Ziinc** [comment]
Or did I misinterpret `UUID_OR_NAME_OR_ID`? From what i read in the issue description, I thought that you're referring to endpoint uuid.

**Comment by Ziinc** [comment]
Closing, moving to internal tracker [here](https://www.notion.so/supabase/Endpoints-v2-88abadc47a15494c890c3c32d05bc83a#9b296f2669a84ec9857a93aaed05db16)
