### ISSUE TITLE
Endpoints prod vs staging

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare#1007]
How do we deal with customers prod vs staging env for Endpoints?

Currently, we suggest creating two Logflare accounts, one for prod and one for staging.  But then to "deploy your endpoint to prod" you must copy and paste it to the prod logflare account which is very error prone.

There must be a better way.

**Comment by Ziinc** [comment]
One way that I can think of, is similar to this https://github.com/Logflare/logflare/issues/1006#issuecomment-979365656

Where each team can create different environments (dev/test/stag/prod/etc..) per team, and the only thing that changes would be the scope parameter after the actual uuid of the LF endpoint. Each environement would point to different sources.

For example: `https://logflare.app/my-team/my-endpoint-query-uuid-123/prod`

This would allow the same query to be used across env, while pointing to the appropriate source for each env.

**Comment by Ziinc** [comment]
Closing, already in internal tracker [here](https://www.notion.so/supabase/Endpoints-v2-88abadc47a15494c890c3c32d05bc83a#865a4ec6f4aa473c94b10d6d62011c98)
