### ISSUE TITLE
Dataset name migration in Endpoint SQL query

### ISSUE THREAD

**Issue by Ziinc** [Logflare/logflare#1010]
When datasets get renamed, the reference table needs to be updated from the old reference name to the new reference name, for e.g. from `logflare` to `my_app`.

Currently LF endpoint queries do not get dynamically updated, and do not have a reference registry for retrieving the correct dataset reference name

**Comment by chasers** [comment]
This is a regression actually. We were doing this.

**Comment by Ziinc** [comment]
source mappings solves this now.
