### ISSUE TITLE
Endpoints should be versioned

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare#1011]
Each update to the Endpoint should be saved as a new version. 

- [ ] Versions should be addressable at `/endpoints/ID_OR_UUID_OR_NAME/VERSION/query`
- [ ] `latest` version should give you the lastest
- [ ] When updating the Endpoint if the query and params are the same, make sure we don't update it and create a new version

**Comment by Ziinc** [comment]
Closing, moving to internal tracker [here](https://www.notion.so/supabase/Endpoints-v2-88abadc47a15494c890c3c32d05bc83a#9b39679fdfb1450a9d6ea86cd8f6222c)
