### ISSUE TITLE
Document how to create more teams

### ISSUE THREAD

**Issue by olivermt** [Logflare/logflare#1050]
I am struggling hard to become a customer with more than my hobby project.
I just spent a solid 15 minutes looking around and I can't see how to make more teams.

Is this simply not possible(the UI certainly implies you can be a member of more than one team)?

**Comment by chasers** [comment]
I can see how this would be confusing. 

A Team is basically an account.  So you would create another account (login with a different email or provider) and then invite your current email to this new account.  Then you can easily switch between teams (accounts) from your dashboard.
