### ISSUE TITLE
Custom routines go out of sync when using team-based prod/staging environments

### ISSUE THREAD

**Issue by Ziinc** [Logflare/logflare#1051]
![image](https://user-images.githubusercontent.com/22714384/147581693-91ede99b-99ea-48c6-a8e3-9b1bd4f62117.png)

Custom bigquery routines go out of sync between different environments, which then requires manually copying over routines.

Another tangential issue is that the name reference to the bigquery routine also differs between each environment, which makes it more error prone when copy-pasting endpoint sql snippets.

**Comment by Ziinc** [comment]
related to #1007

**Comment by chasers** [comment]
All Logflare managed functions are the `LF_` ones.  All the others were manually created inside bq.  This is just the nature of giving Logflare access to a project you have the potential to manage manually.

Really app_supabase_io should only be things Logflare has created ... to keep things contained.  The others were me trying to figure out the best way to support the things we're trying to do with charts.  We can then have it Logflare manage it like you suggested in #1052
