### ISSUE TITLE
Ability to regenerate a source UUID

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare#1057]
So that users can roll an individual source ID vs rolling the ingest API key which affects all the sources.

**Comment by Ziinc** [comment]
Should be superceded by v2 of #1106 , when access tokens covers ingest api as well.

**Comment by Ziinc** [comment]
Moving to internal tracker [here](https://www.notion.so/supabase/Ingest-Access-Tokens-b3cb11881d3e42a2b8880651b8334f05)
Ingestion should  be covered by access tokens as well, which users can then roll. 

Rolling source Id adds unnecessary complexity.
