### ISSUE TITLE
bug: sql through endpoints does not parse newlines correctly

### ISSUE THREAD

**Issue by Ziinc** [Logflare/logflare#1058]
related to https://github.com/supabase/supabase/pull/5303

from my experimentation, seems like newline handling results in an error. Could be that it is not being parsed correctly.

For example, before uri encoding:
```
....&sql=select count(*) \n from edge_logs
```
will result in a server error

**Comment by chasers** [comment]
@Ziinc are you escaping it?  What's the actual param string look like you're sending?

**Comment by chasers** [comment]
Yeah it works if you escape it:

`&sql=select%0A%20timestamp%0Afrom%20ex_logs`

**Comment by Ziinc** [comment]
Hmm it does get escaped, but i think the platform api is removing the newlines. i'll have to do some digging 🕵️
