### ISSUE TITLE
Question on schema fields?

### ISSUE THREAD

**Issue by came** [Logflare/logflare#1065]
Hi there,

I really like logflare, even its colors :P
Now I have a question on max schema fields and how they reset when clicking clear cache?
In the beginning, I logged some huge objects that occupied all fields of the source; can I now just reset the cache and start over again? It seems that I can lock new fields - does that mean I should send some "initial" logs with all fields I need and then just lock new ones?
Wouldn't it even be more helpful to have a way to select the important fields needed for search?

p.s. considering the fact that fields are "limited" I wanted to use a contextData field to JSON.stringify({}, null, 2) more context information as metadata. Unfortunately, the JSON formatting does not respect \n and new lines :/ It would be great if the formatting of JSON.stringify would be respected.

Thanks a lot
BR, Carsten

**Comment by Ziinc** [comment]
We will be preserving raw string rendering to avoid ambiguity in displaying the metadata. Providing a ui option for displaying json-encoded strings is being considered.
please 👍 this comment if you would like to see this feature. This issue will be checked back in a few months time. if there is no/minimal demand this consideration will be dropped.
