### ISSUE TITLE
Can we use OR statements on our LQL queries?

### ISSUE THREAD

**Issue by Mathitos** [Logflare/logflare#1076]
I wish to filter some logs by 2 matchs, like
m.level:"info" OR "ping"
so this would match any log that has level:"info" or "ping" on the message body

**Comment by chasers** [comment]
Hi Mathitos!  Not currently no.

**Comment by Ziinc** [comment]
This likely will not be supported.

It is recommended to use regex OR to achieve this.
```
m.level:~"info|ping"
```
