### ISSUE TITLE
Logflare says none of my schema fields exist

### ISSUE THREAD

**Issue by acarl005** [Logflare/logflare#1159]
I'm getting this error when I try to run the LQL query `metadata.source:lambda` on my logs (see screenshot):

```
LQL parser error: path `metadata.source` not present in source schema
```

![Screen Shot 2022-08-26 at 15 12 28](https://user-images.githubusercontent.com/8334252/186976457-ba313250-bb3a-47bc-a253-d769218f331b.png)

But I have verified that I definitely have that field in my schema, see other screenshot.

![Screen Shot 2022-08-26 at 15 12 37](https://user-images.githubusercontent.com/8334252/186976308-a82a0a65-754b-40be-9909-b620580205da.png)

The same thing is happening for every single field in my schema, it says they are all missing.

**Comment by acarl005** [comment]
I think it **might** have had something to do with the fact that I configured my logger ([pino](https://github.com/pinojs/pino)) to print a duplicate key in my JSON message. I pushed an update to remove the duplicate and now it seems to work fine.

**Comment by chasers** [comment]
Sorry for the confusion. Yeah seems to be working for your source now. I think this is an edge case with the some things we do to cache your schema. There is some major work coming for a v2 BigQuery pipeline (we'll be supporting more backends and also rewriting the BigQuery one) so I think this will get fixed then.

**Comment by charanjit-singh** [comment]
Any updates?

**Comment by Ziinc** [comment]
closing as this is outdated.
