### ISSUE TITLE
Can't delete IPInfo API Key

### ISSUE THREAD

**Issue by alexgarciab** [Logflare/logflare#1162]
Hi there, there is an issue with Logflare + Cloudflare integration where I can't delete the IPInfo API Key.
I tried to edit the app inside Cloudflare, it is deleting the API Key from the field, but it is still making requests on the backend.
Please fix it asap @chasers

**Comment by chasers** [comment]
@alexgarciab did you delete the app entirely from that Cloudflare Zone and re-install?

**Comment by alexgarciab** [comment]
Apparently that worked. Ideally, I should be able to delete the API key from the Cloudflare App without uninstalling the App.
