### ISSUE TITLE
I can't select a domain (disabled) in the sink list of rule

### ISSUE THREAD

**Issue by andgar2010** [Logflare/logflare#1352]
Hi, I am trying with this explanation #608 with the use of LQL field in the filter rules with my domain, but I can't select a domain in the sink list as it is disabled. I have investigated Logflare plan, but I can't find information of filter rules in the plan, until I found this problem.

![Captura de Pantalla 2023-02-05 a la(s) 9 42 48 p m](https://user-images.githubusercontent.com/19521054/216871501-892b363a-1e0f-45a2-9643-e783c11ad346.png)

**Comment by chasers** [comment]
You need to add another source first. Rules copy log events from one source to another with the LQL statement.
