### ISSUE TITLE
what is a field ?

### ISSUE THREAD

**Issue by samipshah100** [Logflare/logflare#1623]
what does it mean 50 fields exceeded?

**Comment by Ziinc** [comment]
Hi @samipshah100 , from the [pricing page](https://logflare.app/pricing),  free users are restricted to 50 schema fields.

Schema fields are columns within BigQuery, which allow you to store data.
The documentation for source schemas can be found here https://docs.logflare.app/concepts/ingestion/#source-schemas

**Comment by samipshah100** [comment]
Thanks. I can't see the schema button in my account

**Comment by Ziinc** [comment]
You will need to click on the search button to enter search mode.
