### ISSUE TITLE
Protecting install

### ISSUE THREAD

**Issue by ghostdevv** [Logflare/logflare#1766]
I've installed Logflare with a postgres backend and want to expose it to the internet so I can use it. I need to protect the UI so going to use basic auth with Caddy for this. All this to ask, what routes are safe to allow through the basic auth, and are required to? Currently allowing `/logs/*` through and nothing else.

**Comment by Ziinc** [comment]
@ghostdevv sorrt for the late reply.
for ingestion only, you can do anything with the `/api/logs` or `/logs` path prefix.
