### ISSUE TITLE
filter own IP at ingest 

### ISSUE THREAD

**Issue by ohitstom** [Logflare/logflare#1840]
how can I fully filter my own IP from actual ingest so it's not something I need to do manually every time I check my logs?

also don't want to make pointless requests to the IP info thing, since I have a self hosted rpc service that pings my site constantly

**Comment by Ziinc** [comment]
hi @ohitstom could you explain your ingestion setup? you could set up drop rules within source settings to drop certain logs on ingest.

**Comment by ohitstom** [comment]
> hi @ohitstom could you explain your ingestion setup? you could set up drop rules within source settings to drop certain logs on ingest.

just domain wide with cloudflare add-ons, I tried setting up a drop rule but it didn't seem to filter

**Comment by Ziinc** [comment]
could you paste in your drop rule here together with a sample of your log event?

Also, might want to reset the source cache so that ingestion processes are reset with the new rules. might be a bug somewhere if it doesn't reset and the rule is valid

**Comment by ohitstom** [comment]
> could you paste in your drop rule here together with a sample of your log event?
> 
> Also, might want to reset the source cache so that ingestion processes are reset with the new rules. might be a bug somewhere if it doesn't reset and the rule is valid

using this rule I can forward them to a sink but when I set it as a rule it doesnt do anything 
`-metadata.request.ipData.ip:"redacted" `

**Comment by ohitstom** [comment]
![Screenshot_20231122-200557.png](https://github.com/Logflare/logflare/assets/22730962/441e010b-f48d-4600-92c3-4493f3f5b00d)

**Comment by Ziinc** [comment]
your rule looks fine, might be that there is a mismatch in your event schema. could you paste in your event schema or a sample of your event?

**Comment by ohitstom** [comment]
> your rule looks fine, might be that there is a mismatch in your event schema. could you paste in your event schema or a sample of your event?

sorry I'm kinda new to this do you have docs on where I can find those or what they are?

**Comment by Ziinc** [comment]
LQl filters are case sensitive, so you would need to use `metdata.request.ipData.ip:~"REDACTED"` using a regex rule

you can refer to the docs here https://docs.logflare.app/concepts/lql/
