### ISSUE TITLE
Unnecessary overflow-x: scroll

### ISSUE THREAD

**Issue by GusGold** [Logflare/logflare#2]
The following `overflow-x: scroll;`

 * https://github.com/Logflare/logflare/blob/8ec7f328cdaf06b6aa4e7730676cbfc4871b81e3/assets/css/app.css#L19
 * https://github.com/Logflare/logflare/blob/8ec7f328cdaf06b6aa4e7730676cbfc4871b81e3/assets/css/app.css#L239
 * https://github.com/Logflare/logflare/blob/8ec7f328cdaf06b6aa4e7730676cbfc4871b81e3/assets/css/app.css#L278

And the following `overflow-y: scroll;`

 * https://github.com/Logflare/logflare/blob/8ec7f328cdaf06b6aa4e7730676cbfc4871b81e3/assets/css/app.css#L272

cause unnecessary scroll bars to appear in both Chome V72 and Firefox V64.

With `scroll`:

![image](https://user-images.githubusercontent.com/2942675/52992077-fc884200-345a-11e9-9e94-34c165fd354f.png)

versus without `scroll`:

![image](https://user-images.githubusercontent.com/2942675/52992129-2477a580-345b-11e9-8a79-6bcc0e1ca3e4.png)

Also, `.subhead h5`'s line height is too large, or its container `.subhead .container` is too short such that a vertical scroll bar appears.

**Comment by chasers** [comment]
Yeah that was mostly a quick fix for mobile but will figure something else out tomorrow.

**Comment by chasers** [comment]
Try it now...

**Comment by chasers** [comment]
Oh and feel free to turn your worker back on.  Would love the usage.  Also, I have submitted our Cloudflare App to their app store, so when that is approved neither of us will have to pay for worker usage, at least in the short term.
