### ISSUE TITLE
Help: I have my sourceId + apiKey + email, but when I login, it's like my account was completely reset

### ISSUE THREAD

**Issue by peterpme** [Logflare/logflare#2205]
Hi there,

I have my sourceId + apiKey + email.

No matter how I try to login (email, Google OAuth, Github), my account is completely blank.

Did something get reset? Did I mess something up?

Is there anyone I can talk to to reverse engineer this and figure out what account this is under?

Thank you!

**Comment by Ziinc** [comment]
Hi, could you send in an email to support@supabase.com which is the appropriate support line for such queries.
You should clear cache and try to log in with the initial auth method that you had used on account setup.
