### ISSUE TITLE
Trojan Horse

### ISSUE THREAD

**Issue by 1lllllllIl** [Logflare/logflare#29]
The default permissions this app requires on Github are **outrageous** - quick clicking fools who don't notice the full complete repo access requirements will loose all their proprietary source code company secrets  to some Chase Granberry fella who fishes for them on the Cloudflare App Store

![permission bandit](https://httpsimage.com/v2/de755079-f2f5-4ad8-ab46-576fa4813e5c.png)

**Comment by chasers** [comment]
False ... right there in the screenshot it says `public repository data`.

And here is the config: https://github.com/Logflare/logflare/blob/master/config/config.exs#L28

**Comment by mhajder** [comment]
@chasers But why do you need full access to all public repositories?

**Comment by chasers** [comment]
@mhajder fix for this should be rolled out tomorrow morning!

**Comment by n3rdb3rry** [comment]
On production!

**Comment by chasers** [comment]
On production!
