### ISSUE TITLE
406 Not Acceptable error

### ISSUE THREAD

**Issue by kraiovsky** [Logflare/logflare#480]
Hello,

I am trying to log page visit/navigation events in Next.js/Vercel project.
Experimenting with two ways of doing so - calling Logflare API on page render through `getServerSideProps` or at `_app.js` level using `Router` events.

Either way, I am calling `POST https://api.logflare.app/logs` sending api key and source id; first couple calls go through well, however all consecutive requests fail with `406 Not Acceptable` response.

Am I doing anything wrong?

thanks
Roman

**Comment by chasers** [comment]
Hi Roman!  

406 means you're sending a payload which is not compatible with your source schema, or your fields are not compatible with BigQuery column names.  If it's a new source it's probably something in the field names. 

If you're logging in the router, are you logging request / response headers?  If so you'll need to change dashes to underscores before sending those over. If you want to email me at support@logflare.app with a link to your source I can look at it.
