### ISSUE TITLE
Suggestion: Pow for user management

### ISSUE THREAD

**Issue by danschultzer** [Logflare/logflare#6]
Cool project!

I'm working on getting `:ex_oauth2_provider` and `:phoenix_oauth2_provider` up to date soon so you can pull a release version from hex rather than the github branch!

I've two other libraries [Pow](https://github.com/danschultzer/pow) and [PowAssent](https://github.com/danschultzer/pow_assent) that you can use for user management. Since you already have a setup running with Ueberauth you won't need it, but I thought it may be worth to consider offloading user management and security in the future.

**Comment by chasers** [comment]
Yeah user management is probably up pretty soon so I’ll check those out. 

I’ll keep an eye out for updates to the oauth2 stuff too. If you that about and can ping me when they’re ready I’ll give em a go.

**Comment by danschultzer** [comment]
Sure! I'll close this issue.
