### ISSUE TITLE
Filter what to be logged?

### ISSUE THREAD

**Issue by Hazmi35** [Logflare/logflare#608]
Can we filter some requests with User-Agents or IP Addresses for not showing up in logging?

**Comment by chasers** [comment]
Yep! You can use a `-` before any LQL field query. So like `-metadata.request.ip_address:"1.1.1.1"` will query for all events except what matches that query.  Or to filter out any bot user agents you can do `-metadata.request.user_agent:~"bot"` which uses regex to match `bot` if it exists in the user agent string. Note: your actual field accessor may vary.

This also works with routing, so you can set up another source ... add an LQL rule on your ingest source like an example above and all events except those will get routed to your other source.

**Comment by Hazmi35** [comment]
Ah I see. Thanks.

**Comment by andgar2010** [comment]
Hi, I am trying with this explanation with the use of LQL field in the filter rules with my domain, but I can't select a domain in the sink list as it is disabled. I have investigated Logflare plan, but I can't find information of filter rules in the plan, until I found this problem.

![Captura de Pantalla 2023-02-05 a la(s) 9 42 48 p m](https://user-images.githubusercontent.com/19521054/216871501-892b363a-1e0f-45a2-9643-e783c11ad346.png)
