### ISSUE TITLE
Remove cdn-cgi <script/>

### ISSUE THREAD

**Issue by brillout** [Logflare/logflare#611]
Logflare seems to inject `<script src="/cdn-cgi/apps/head/CwZAXCxXxBUK433NttOcg6GXln4.js"></script>`. Is it necessary? How can I remove it?

**Comment by chasers** [comment]
Unfortunately, it can't be removed. Cloudflare injects those even when an app doesn't ship any js (ours does not).

**Comment by brillout** [comment]
Ok, thanks for the clarification!
