### ISSUE TITLE
stream_1.default.Writable is not a constructor 

### ISSUE THREAD

**Issue by timakhalaya** [Logflare/logflare#847]
TypeError: stream_1.default.Writable is not a constructor
const { send, stream } = logflarePinoVercel({ apiKey, sourceToken })
using in next.js app 
 "dependencies": {
        "pino": "6.11.2",
        "pino-logflare": "0.3.8"
    }

**Comment by chasers** [comment]
Thanks, added this to the pino-logflare project.

https://github.com/Logflare/pino-logflare/issues/20
