### ISSUE TITLE
Webhook sender

### ISSUE THREAD

**Issue by FreshImmuc** [Logflare/logflare#982]
Hey, is there a possible way to send specific logs or "log placeholders" like the user agent to a webhook?

**Comment by chasers** [comment]
Hi! Sorry for the delay here ... yes, if you edit the source and scroll down to the `Custom Event Message` section you can pick data out from the metadata to include in the log stream, which will then get included in the webhook so you can see that where the webhook goes. Let me know if this works for you or not 🙏
